language: php

php:
  - 7.2
  - 7.3

matrix:
  fast_finish: true

before_script:
  - if [[ $TRAVIS_PHP_VERSION = "7.2" ]]; then pecl install zip; fi
  - composer update --prefer-stable

script: ./vendor/bin/phpunit

after_script:
    - php vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
