language: php

php:
  - 7.1
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
      - php: hhvm
      - php: nightly

before_script:
  - composer update --prefer-stable

script: ./vendor/bin/phpunit

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml; fi;'
