language: php

php:
  - 7.1
  - nightly

matrix:
  fast_finish: true
  allow_failures:
      - php: nightly

before_script:
  - composer update --prefer-stable

script: ./vendor/bin/phpunit

after_script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then php vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml; fi
